// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package commands

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type QuestionType string

const (
	QuestionTypeOrdinalSingle   QuestionType = "ordinal_single"
	QuestionTypeNominalSingle   QuestionType = "nominal_single"
	QuestionTypeNominalMultible QuestionType = "nominal_multible"
	QuestionTypeOrder           QuestionType = "order"
	QuestionTypeBoolean         QuestionType = "boolean"
)

func (e *QuestionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestionType(s)
	case string:
		*e = QuestionType(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestionType: %T", src)
	}
	return nil
}

type NullQuestionType struct {
	QuestionType QuestionType
	Valid        bool // Valid is true if QuestionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestionType) Scan(value interface{}) error {
	if value == nil {
		ns.QuestionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestionType), nil
}

type Role string

const (
	RoleOwner       Role = "owner"
	RoleEditor      Role = "editor"
	RoleAnalyst     Role = "analyst"
	RoleProctor     Role = "proctor"
	RoleParticipant Role = "participant"
	RoleSpectator   Role = "spectator"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role
	Valid bool // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type Answer struct {
	ID         int64
	QuestionID int64
	UserID     int64
	Value      pgtype.Int4
}

type AnswerOption struct {
	ID       int64
	AnswerID int64
	OptionID int64
	Position int32
}

type Checklist struct {
	ID   int64
	Name pgtype.Text
}

type Option struct {
	ID         int64
	QuestionID int64
	Position   int32
	Option     string
}

type Poll struct {
	ID             int64
	Title          string
	TemplatePollID int64
}

type Question struct {
	ID       int64
	PollID   int64
	Question string
	Type     QuestionType
}

type Session struct {
	ID                   string
	UserID               int32
	ExpiresAt            pgtype.Timestamp
	AccessToken          pgtype.Text
	AccessTokenExpiresAt pgtype.Text
	RefreshToken         pgtype.Text
}

type Todo struct {
	ID          int64
	Completed   bool
	Text        string
	ChecklistID int64
}

type User struct {
	ID         int64
	Username   string
	KeycloakID pgtype.UUID
}

type UsersChecklist struct {
	UserID      int64
	ChecklistID int64
	Relation    pgtype.Text
}

type UsersPoll struct {
	UserID int64
	PollID int64
	Role   Role
}
