// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: polls.sql

package commands

import (
	"context"
)

const assignUserToPoll = `-- name: AssignUserToPoll :one
INSERT INTO users_polls (user_id, poll_id, role)
VALUES ($1, $2, $3)
RETURNING user_id, poll_id, role
`

type AssignUserToPollParams struct {
	UserID int64
	PollID int64
	Role   Role
}

func (q *Queries) AssignUserToPoll(ctx context.Context, arg AssignUserToPollParams) (UsersPoll, error) {
	row := q.db.QueryRow(ctx, assignUserToPoll, arg.UserID, arg.PollID, arg.Role)
	var i UsersPoll
	err := row.Scan(&i.UserID, &i.PollID, &i.Role)
	return i, err
}

const createPoll = `-- name: CreatePoll :one
INSERT INTO polls (title, template_poll_id)
VALUES ($1, $2)
RETURNING id, title, template_poll_id
`

type CreatePollParams struct {
	Title          string
	TemplatePollID int64
}

func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) (Poll, error) {
	row := q.db.QueryRow(ctx, createPoll, arg.Title, arg.TemplatePollID)
	var i Poll
	err := row.Scan(&i.ID, &i.Title, &i.TemplatePollID)
	return i, err
}

const deletePoll = `-- name: DeletePoll :one
DELETE FROM polls
WHERE id = $1
RETURNING id, title, template_poll_id
`

func (q *Queries) DeletePoll(ctx context.Context, id int64) (Poll, error) {
	row := q.db.QueryRow(ctx, deletePoll, id)
	var i Poll
	err := row.Scan(&i.ID, &i.Title, &i.TemplatePollID)
	return i, err
}

const removeUserFromPoll = `-- name: RemoveUserFromPoll :one
DELETE FROM users_polls
WHERE user_id = $1 AND poll_id = $2
RETURNING user_id, poll_id
`

type RemoveUserFromPollParams struct {
	UserID int64
	PollID int64
}

type RemoveUserFromPollRow struct {
	UserID int64
	PollID int64
}

func (q *Queries) RemoveUserFromPoll(ctx context.Context, arg RemoveUserFromPollParams) (RemoveUserFromPollRow, error) {
	row := q.db.QueryRow(ctx, removeUserFromPoll, arg.UserID, arg.PollID)
	var i RemoveUserFromPollRow
	err := row.Scan(&i.UserID, &i.PollID)
	return i, err
}

const updatePoll = `-- name: UpdatePoll :one
UPDATE polls
SET title = $1, template_poll_id = $2
WHERE id = $3
RETURNING id, title, template_poll_id
`

type UpdatePollParams struct {
	Title          string
	TemplatePollID int64
	ID             int64
}

func (q *Queries) UpdatePoll(ctx context.Context, arg UpdatePollParams) (Poll, error) {
	row := q.db.QueryRow(ctx, updatePoll, arg.Title, arg.TemplatePollID, arg.ID)
	var i Poll
	err := row.Scan(&i.ID, &i.Title, &i.TemplatePollID)
	return i, err
}
