// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: questions.sql

package commands

import (
	"context"
)

const createOptionForQuestion = `-- name: CreateOptionForQuestion :one
INSERT INTO options (question_id, option, position)
VALUES ($1, $2, $3)
RETURNING id, question_id, option, position
`

type CreateOptionForQuestionParams struct {
	QuestionID int64
	Option     string
	Position   int32
}

type CreateOptionForQuestionRow struct {
	ID         int64
	QuestionID int64
	Option     string
	Position   int32
}

func (q *Queries) CreateOptionForQuestion(ctx context.Context, arg CreateOptionForQuestionParams) (CreateOptionForQuestionRow, error) {
	row := q.db.QueryRow(ctx, createOptionForQuestion, arg.QuestionID, arg.Option, arg.Position)
	var i CreateOptionForQuestionRow
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Option,
		&i.Position,
	)
	return i, err
}

const createQuestionForPoll = `-- name: CreateQuestionForPoll :one
INSERT INTO questions (poll_id, question, type)
VALUES ($1, $2, $3)
RETURNING id, poll_id, question, type
`

type CreateQuestionForPollParams struct {
	PollID   int64
	Question string
	Type     QuestionType
}

func (q *Queries) CreateQuestionForPoll(ctx context.Context, arg CreateQuestionForPollParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestionForPoll, arg.PollID, arg.Question, arg.Type)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.Question,
		&i.Type,
	)
	return i, err
}

const removeOptionFromQuestion = `-- name: RemoveOptionFromQuestion :one
DELETE FROM options
WHERE id = $1
RETURNING id, question_id, option
`

type RemoveOptionFromQuestionRow struct {
	ID         int64
	QuestionID int64
	Option     string
}

func (q *Queries) RemoveOptionFromQuestion(ctx context.Context, id int64) (RemoveOptionFromQuestionRow, error) {
	row := q.db.QueryRow(ctx, removeOptionFromQuestion, id)
	var i RemoveOptionFromQuestionRow
	err := row.Scan(&i.ID, &i.QuestionID, &i.Option)
	return i, err
}

const removeQuestionFromPoll = `-- name: RemoveQuestionFromPoll :one
DELETE FROM questions
WHERE id = $1
RETURNING id, poll_id, question, type
`

func (q *Queries) RemoveQuestionFromPoll(ctx context.Context, id int64) (Question, error) {
	row := q.db.QueryRow(ctx, removeQuestionFromPoll, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.Question,
		&i.Type,
	)
	return i, err
}
