// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: polls.sql

package queries

import (
	"context"
)

const findPollForUser = `-- name: FindPollForUser :one
SELECT p.id, p.title, p.template_poll_id,
       up.role
FROM polls p
JOIN users_polls up ON p.id = up.poll_id
WHERE up.user_id = $1 AND p.id = $2
`

type FindPollForUserParams struct {
	UserID int64
	ID     int64
}

type FindPollForUserRow struct {
	ID             int64
	Title          string
	TemplatePollID int64
	Role           Role
}

func (q *Queries) FindPollForUser(ctx context.Context, arg FindPollForUserParams) (FindPollForUserRow, error) {
	row := q.db.QueryRow(ctx, findPollForUser, arg.UserID, arg.ID)
	var i FindPollForUserRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TemplatePollID,
		&i.Role,
	)
	return i, err
}

const listPollsForUser = `-- name: ListPollsForUser :many
SELECT p.id, p.title, p.template_poll_id,
       up.role
FROM polls p
JOIN users_polls up ON p.id = up.poll_id
WHERE up.user_id = $1
ORDER BY p.title
`

type ListPollsForUserRow struct {
	ID             int64
	Title          string
	TemplatePollID int64
	Role           Role
}

func (q *Queries) ListPollsForUser(ctx context.Context, userID int64) ([]ListPollsForUserRow, error) {
	rows, err := q.db.Query(ctx, listPollsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPollsForUserRow
	for rows.Next() {
		var i ListPollsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TemplatePollID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
