// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: questions.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countQuestionsForPoll = `-- name: CountQuestionsForPoll :one
SELECT COUNT(*)
FROM questions q
WHERE q.poll_id = $1
`

func (q *Queries) CountQuestionsForPoll(ctx context.Context, pollID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countQuestionsForPoll, pollID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findOption = `-- name: FindOption :one
SELECT o.id, o.question_id, o.option, o.position
FROM options o
WHERE o.id = $1
`

type FindOptionRow struct {
	ID         int64
	QuestionID int64
	Option     string
	Position   int32
}

func (q *Queries) FindOption(ctx context.Context, id int64) (FindOptionRow, error) {
	row := q.db.QueryRow(ctx, findOption, id)
	var i FindOptionRow
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Option,
		&i.Position,
	)
	return i, err
}

const findQuestion = `-- name: FindQuestion :one
SELECT q.id, q.poll_id, q.question, q.type
FROM questions q
WHERE q.id = $1
`

func (q *Queries) FindQuestion(ctx context.Context, id int64) (Question, error) {
	row := q.db.QueryRow(ctx, findQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.Question,
		&i.Type,
	)
	return i, err
}

const findQuestionForPoll = `-- name: FindQuestionForPoll :one
SELECT q.id, q.poll_id, q.question, q.type
FROM questions q
WHERE q.poll_id = $1 AND q.id = $2
`

type FindQuestionForPollParams struct {
	PollID int64
	ID     int64
}

func (q *Queries) FindQuestionForPoll(ctx context.Context, arg FindQuestionForPollParams) (Question, error) {
	row := q.db.QueryRow(ctx, findQuestionForPoll, arg.PollID, arg.ID)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.Question,
		&i.Type,
	)
	return i, err
}

const listOptionsForQuestion = `-- name: ListOptionsForQuestion :many
SELECT o.id, o.question_id, o.option, o.position
FROM options o
WHERE o.question_id = $1
ORDER BY o.position
`

type ListOptionsForQuestionRow struct {
	ID         int64
	QuestionID int64
	Option     string
	Position   int32
}

func (q *Queries) ListOptionsForQuestion(ctx context.Context, questionID int64) ([]ListOptionsForQuestionRow, error) {
	rows, err := q.db.Query(ctx, listOptionsForQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOptionsForQuestionRow
	for rows.Next() {
		var i ListOptionsForQuestionRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Option,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsForPoll = `-- name: ListQuestionsForPoll :many
SELECT q.id, q.poll_id, q.question, q.type
FROM questions q
WHERE q.poll_id = $1
ORDER BY q.id
`

func (q *Queries) ListQuestionsForPoll(ctx context.Context, pollID int64) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsForPoll, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.PollID,
			&i.Question,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsForPollWithOptions = `-- name: ListQuestionsForPollWithOptions :many
SELECT q.id, q.poll_id, q.question, q.type,
       o.id AS option_id, o.option, o.position
FROM questions q
LEFT JOIN options o ON q.id = o.question_id
WHERE q.poll_id = $1
ORDER BY q.id, o.position
`

type ListQuestionsForPollWithOptionsRow struct {
	ID       int64
	PollID   int64
	Question string
	Type     QuestionType
	OptionID pgtype.Int8
	Option   pgtype.Text
	Position pgtype.Int4
}

func (q *Queries) ListQuestionsForPollWithOptions(ctx context.Context, pollID int64) ([]ListQuestionsForPollWithOptionsRow, error) {
	rows, err := q.db.Query(ctx, listQuestionsForPollWithOptions, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestionsForPollWithOptionsRow
	for rows.Next() {
		var i ListQuestionsForPollWithOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PollID,
			&i.Question,
			&i.Type,
			&i.OptionID,
			&i.Option,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
