// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findActiveSession = `-- name: FindActiveSession :one
SELECT s.id, s.user_id, s.expires_at
FROM sessions s
WHERE s.id = $1 AND s.expires_at > NOW()
`

type FindActiveSessionRow struct {
	ID        string
	UserID    int32
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) FindActiveSession(ctx context.Context, id string) (FindActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, findActiveSession, id)
	var i FindActiveSessionRow
	err := row.Scan(&i.ID, &i.UserID, &i.ExpiresAt)
	return i, err
}

const findSession = `-- name: FindSession :one
SELECT s.id, s.user_id, s.expires_at
FROM sessions s
WHERE s.id = $1
`

type FindSessionRow struct {
	ID        string
	UserID    int32
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) FindSession(ctx context.Context, id string) (FindSessionRow, error) {
	row := q.db.QueryRow(ctx, findSession, id)
	var i FindSessionRow
	err := row.Scan(&i.ID, &i.UserID, &i.ExpiresAt)
	return i, err
}
