DROP TABLE IF EXISTS "answer_option" CASCADE;
DROP TABLE IF EXISTS "answers" CASCADE;
DROP TABLE IF EXISTS "options" CASCADE;
DROP TABLE IF EXISTS "questions" CASCADE;
DROP TABLE IF EXISTS "users_polls" CASCADE;
DROP TABLE IF EXISTS "polls" CASCADE;
DROP TABLE IF EXISTS "users_checklists" CASCADE;
DROP TABLE IF EXISTS "todos" CASCADE;
DROP TABLE IF EXISTS "sessions" CASCADE;
DROP TABLE IF EXISTS "checklists" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

DROP INDEX IF EXISTS "users_username_key";

DROP TYPE IF EXISTS "role";
DROP TYPE IF EXISTS "question_type";